#!/usr/bin/env python3
"""graph.py — the NPC relationship graph, as a Mermaid diagram inside WORLD.md.

Reads the structured relationship fields on each `npcs/<name>.md` (and on factions in
`FACTIONS.md`), then writes two graphs:

- a **player-safe** one into `campaigns/<slug>/WORLD.md`, covering only ties the player has
  actually learned in play;
- a **full** one into `campaigns/<slug>/gm-private/relationships.md`, including hidden
  allegiances.

The player-safe graph is the default output. The GM one is only ever written to
`gm-private/`, never printed unless `--gm` is passed explicitly.

Mermaid renders on GitHub and in most Markdown viewers with nothing to install, so there is
no runtime dependency. The dashboard shows the same data as a plain adjacency list, because
it must not fetch a diagramming script.

Opt-in per campaign: worth the most in intrigue and faction play, noise in a dungeon crawl.
Standard library only.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any, Iterable, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parent))

from roll import atomic_write, campaign_dir, repo_root, world_dir  # noqa: E402
import pf2e  # noqa: E402

TIE_KINDS = ("ally-of", "rival-of", "owes", "owed-by", "serves", "related-to", "fears")

ARROWS = {
    "ally-of": ("-->", "ally of"),
    "rival-of": ("-.->", "rival of"),
    "owes": ("-->", "owes"),
    "owed-by": ("-->", "owed by"),
    "serves": ("==>", "serves"),
    "related-to": ("---", "kin"),
    "fears": ("-.->", "fears"),
}

GM_MARKERS = ("gm-only", "gmonly", "gm only", "secret")
UNKNOWN_MARKERS = ("unknown", "not-known", "unlearned", "hidden-from-player")

BEGIN = "<!-- RELATIONSHIP-GRAPH:BEGIN (generated by tools/graph.py — do not hand-edit) -->"
END = "<!-- RELATIONSHIP-GRAPH:END -->"

_TIE_RE = re.compile(
    r"^\s*[-*]\s*\**(" + "|".join(TIE_KINDS) + r")\**\s*:\s*(.+?)\s*$", re.IGNORECASE
)
_NAME_RE = re.compile(r"^\s*#\s+(.+?)\s*$", re.MULTILINE)


class GraphError(Exception):
    pass


def _node_id(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "_", name.strip()).strip("_")
    return s or "n"


def _strip_markers(text: str) -> tuple[str, bool, bool]:
    """Pull `[gm-only]`, `(GM-ONLY)`, `<!-- gm-only -->` and `[unknown]` off a tie line."""
    gm = False
    unknown = False
    lowered = text.lower()
    for m in GM_MARKERS:
        if f"[{m}]" in lowered or f"({m})" in lowered or f"<!-- {m} -->" in lowered:
            gm = True
    for m in UNKNOWN_MARKERS:
        if f"[{m}]" in lowered or f"({m})" in lowered:
            unknown = True
    cleaned = re.sub(r"\[[^\]]*\]|\([Gg][Mm][^)]*\)|<!--.*?-->", "", text).strip(" .;,-")
    return cleaned, gm, unknown


def parse_ties(path: Path) -> tuple[str, list[dict[str, Any]]]:
    text = path.read_text(encoding="utf-8")
    m = _NAME_RE.search(text)
    who = (m.group(1).strip() if m else path.stem).strip()
    # Strip a leading "GM-ONLY" fence marker from the heading if one leaked in.
    ties: list[dict[str, Any]] = []
    in_gm_block = False
    for line in text.splitlines():
        if re.match(r"^\s*>\s*\*\*GM-ONLY\*\*", line, re.IGNORECASE):
            in_gm_block = True
            continue
        if in_gm_block and not line.strip().startswith(">") and line.strip():
            in_gm_block = False
        tm = _TIE_RE.match(line.lstrip("> ").rstrip() if in_gm_block else line)
        if not tm:
            continue
        kind = tm.group(1).lower()
        body, gm, unknown = _strip_markers(tm.group(2))
        if in_gm_block:
            gm = True
        if not body:
            continue
        if "—" in body:
            target, reason = body.split("—", 1)
        elif " - " in body:
            target, reason = body.split(" - ", 1)
        elif ":" in body:
            target, reason = body.split(":", 1)
        else:
            target, reason = body, ""
        ties.append(
            {
                "from": who,
                "kind": kind,
                "to": target.strip().strip("*`"),
                "reason": reason.strip(),
                "gm_only": gm,
                "unknown": unknown,
                "file": str(path),
            }
        )
    return who, ties


def collect(slug: str, include_world: bool) -> tuple[list[str], list[dict[str, Any]]]:
    cdir = campaign_dir(slug)
    if not cdir.is_dir():
        raise GraphError(f"no campaign folder at {cdir}")
    people: list[str] = []
    ties: list[dict[str, Any]] = []
    sources = [cdir / "npcs", cdir / "characters"]
    if include_world:
        w = _world_of(slug)
        if w:
            sources.append(world_dir(w) / "npcs")
    for d in sources:
        if not d.is_dir():
            continue
        for p in sorted(d.glob("*.md")):
            if p.name in ("ROSTER.md", "PARTY.md"):
                continue
            who, t = parse_ties(p)
            people.append(who)
            ties += t
    for name in ("FACTIONS.md",):
        for base in ([cdir] + ([world_dir(_world_of(slug))] if include_world and _world_of(slug) else [])):
            p = base / name
            if p.is_file():
                who, t = parse_ties(p)
                ties += t
    return people, ties


def _world_of(slug: str) -> str | None:
    p = campaign_dir(slug) / "CAMPAIGN.md"
    if not p.exists():
        return None
    v = pf2e.read_field(p.read_text(encoding="utf-8"), "World")
    if v is None:
        return None
    v = v.strip().strip("`")
    return None if v.lower() in ("none", "-", "—", "") else v.split("/")[-1]


def mermaid(ties: list[dict[str, Any]], people: Iterable[str]) -> str:
    nodes: dict[str, str] = {}
    for name in people:
        nodes.setdefault(name, _node_id(name))
    for t in ties:
        nodes.setdefault(t["from"], _node_id(t["from"]))
        nodes.setdefault(t["to"], _node_id(t["to"]))
    lines = ["```mermaid", "graph LR"]
    for name, nid in nodes.items():
        lines.append(f'    {nid}["{name}"]')
    if not ties:
        lines.append("    %% no relationship fields found yet")
    for t in ties:
        arrow, label = ARROWS.get(t["kind"], ("-->", t["kind"]))
        text = label + (f": {t['reason']}" if t["reason"] else "")
        text = text.replace('"', "'")[:60]
        lines.append(f'    {nodes[t["from"]]} {arrow}|"{text}"| {nodes[t["to"]]}')
    lines.append("```")
    return "\n".join(lines)


def adjacency(ties: list[dict[str, Any]]) -> str:
    """The same data as a plain list, for the dashboard, which fetches nothing at runtime."""
    by: dict[str, list[str]] = {}
    for t in ties:
        by.setdefault(t["from"], []).append(
            f"{t['kind'].replace('-', ' ')} {t['to']}" + (f" ({t['reason']})" if t["reason"] else "")
        )
    return "\n".join(f"- **{k}** — " + "; ".join(v) for k, v in sorted(by.items())) or "- _(no ties recorded)_"


def splice(path: Path, block: str, heading: str) -> None:
    body = f"{BEGIN}\n\n## {heading}\n\n{block}\n\n{END}"
    if path.exists():
        text = path.read_text(encoding="utf-8")
        if BEGIN in text and END in text:
            head, rest = text.split(BEGIN, 1)
            _, tail = rest.split(END, 1)
            atomic_write(path, head + body + tail)
            return
        atomic_write(path, text.rstrip() + "\n\n" + body + "\n")
        return
    atomic_write(path, body + "\n")


def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="graph.py", description="NPC relationship graph into WORLD.md.")
    ap.add_argument("--campaign", required=True)
    ap.add_argument("--include-world", action="store_true", help="also read the shared world's npcs/")
    ap.add_argument("--gm", action="store_true", help="print the GM graph to stdout as well as writing it")
    ap.add_argument("--print", dest="show", action="store_true", help="print the player-safe graph")
    ap.add_argument("--adjacency", action="store_true", help="print the player-safe adjacency list")
    args = ap.parse_args(argv)

    try:
        people, ties = collect(args.campaign, args.include_world)
    except GraphError as exc:
        print(f"graph.py: {exc}", file=sys.stderr)
        return 2

    safe = [t for t in ties if not t["gm_only"] and not t["unknown"]]
    hidden = [t for t in ties if t["gm_only"] or t["unknown"]]

    cdir = campaign_dir(args.campaign)
    splice(
        cdir / "WORLD.md",
        mermaid(safe, people)
        + "\n\nWhat the player has learned in play. Regenerate with "
        + f"`python3 tools/graph.py --campaign {args.campaign}` whenever the roster changes.",
        "Relationships",
    )
    gm_path = cdir / "gm-private" / "relationships.md"
    splice(
        gm_path,
        "> **GM-ONLY.** Includes hidden allegiances and ties the player has not learned.\n\n"
        + mermaid(ties, people)
        + f"\n\n{len(hidden)} tie(s) here are absent from the player-safe graph in WORLD.md.",
        "Relationships (full)",
    )

    print(f"{len(safe)} player-safe tie(s) → campaigns/{args.campaign}/WORLD.md")
    print(f"{len(ties)} total tie(s) → campaigns/{args.campaign}/gm-private/relationships.md")
    if hidden:
        print(f"{len(hidden)} tie(s) marked gm-only or unknown are in the GM graph only.")
    if args.show:
        print()
        print(mermaid(safe, people))
    if args.adjacency:
        print()
        print(adjacency(safe))
    if args.gm:
        print()
        print("> **GM-ONLY**")
        print(mermaid(ties, people))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
